spring.application.name=Smart Work Force Management

#spring.datasource.url=jdbc:mysql://localhost:3306/smartdb?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=Ullas@2001
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enables H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL statements in logs
spring.jpa.show-sql=true

# Hibernate / JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect