spring.application.name=Smart Work Force Management

spring.datasource.url=jdbc:mysql://localhost:3306/smartdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ullas@2001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwtSecret=mySuperSecretKey123456789
app.jwtExpirationMs=900000
app.jwtRefreshExpirationMs=604800000
